# Stage 1: Build the React app
FROM node:20 AS build
WORKDIR /app
# Define a build argument

COPY package*.json ./
RUN npm install

COPY .env.production .env.production 

COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
# Copy build output from previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 (default for Nginx)
EXPOSE 80

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
